language: rust
rust: stable
cache: cargo

os: 
  - linux
  - osx
  - windows
before_deploy: 
  - cargo build --release --verbose
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      choco install zip;
      zip -j socks2http-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG}.zip ./target/release/socks2http.exe;
    else 
      zip -j socks2http-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG}.zip ./target/release/socks2http;
    fi
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: socks2http-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
  draft: true